# Store your secrets here. Do not commit this file to version control.
# Get your Gemini API key from https://aistudio.google.com/app/apikey

GEMINI_API_KEY = "AIzaSyBEma9ndSH9UI04FK83jfFH-kHmW_N_ge8
